name: Test trigger action

on:
  push:
    paths:
      - 'docspace-trigger/**'
env:
  TARGETS: "site-core"
jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch Action
        run: |
          curl \
          -X POST \
          -u "${{ secrets.USERNAME}}:${{secrets.TOKEN}}" \
          "https://api.github.com/repos/sk81biz/docspace-build/dispatches" \
          -H "Accept: application/vnd.github.everest-preview+json" \
          --data '{"event_type": "server-trigger-action", "client_payload": { "branches": ["'"${GITHUB_REF_NAME}"'"], "targets": "'"${TARGETS}"'" }}'
